-- +goose Up
CREATE TABLE chats (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    chat_id INTEGER UNIQUE NOT NULL,
    title TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE topups ADD COLUMN chat_id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE quotes ADD COLUMN chat_id INTEGER NOT NULL DEFAULT 0;

-- +goose Down
DROP TABLE chats;
