// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: address_assignments.sql

package db

import (
	"context"
)

const createAddressAssignment = `-- name: CreateAddressAssignment :one
INSERT INTO address_assignments (assigned_to_id, assigned_to_type)
VALUES (?, ?)
RETURNING id, assigned_to_id, assigned_to_type, created_at
`

type CreateAddressAssignmentParams struct {
	AssignedToID   int64
	AssignedToType string
}

func (q *Queries) CreateAddressAssignment(ctx context.Context, arg CreateAddressAssignmentParams) (AddressAssignment, error) {
	row := q.db.QueryRowContext(ctx, createAddressAssignment, arg.AssignedToID, arg.AssignedToType)
	var i AddressAssignment
	err := row.Scan(
		&i.ID,
		&i.AssignedToID,
		&i.AssignedToType,
		&i.CreatedAt,
	)
	return i, err
}

const getAddressAssignment = `-- name: GetAddressAssignment :one
SELECT id, assigned_to_id, assigned_to_type, created_at
FROM address_assignments
WHERE assigned_to_id = ? AND assigned_to_type = ?
`

type GetAddressAssignmentParams struct {
	AssignedToID   int64
	AssignedToType string
}

func (q *Queries) GetAddressAssignment(ctx context.Context, arg GetAddressAssignmentParams) (AddressAssignment, error) {
	row := q.db.QueryRowContext(ctx, getAddressAssignment, arg.AssignedToID, arg.AssignedToType)
	var i AddressAssignment
	err := row.Scan(
		&i.ID,
		&i.AssignedToID,
		&i.AssignedToType,
		&i.CreatedAt,
	)
	return i, err
}

const listAddressAssignments = `-- name: ListAddressAssignments :many
SELECT id, assigned_to_id, assigned_to_type, created_at
FROM address_assignments
ORDER BY id
`

func (q *Queries) ListAddressAssignments(ctx context.Context) ([]AddressAssignment, error) {
	rows, err := q.db.QueryContext(ctx, listAddressAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AddressAssignment
	for rows.Next() {
		var i AddressAssignment
		if err := rows.Scan(
			&i.ID,
			&i.AssignedToID,
			&i.AssignedToType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
