// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_requests.sql

package db

import (
	"context"
	"database/sql"
)

const insertAPIRequest = `-- name: InsertAPIRequest :exec
INSERT INTO api_requests (provider, method, url, request_headers, request_body,
    response_status, response_headers, response_body, duration_ms, error)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAPIRequestParams struct {
	Provider        string
	Method          string
	Url             string
	RequestHeaders  sql.NullString
	RequestBody     sql.NullString
	ResponseStatus  sql.NullInt64
	ResponseHeaders sql.NullString
	ResponseBody    sql.NullString
	DurationMs      sql.NullInt64
	Error           sql.NullString
}

func (q *Queries) InsertAPIRequest(ctx context.Context, arg InsertAPIRequestParams) error {
	_, err := q.db.ExecContext(ctx, insertAPIRequest,
		arg.Provider,
		arg.Method,
		arg.Url,
		arg.RequestHeaders,
		arg.RequestBody,
		arg.ResponseStatus,
		arg.ResponseHeaders,
		arg.ResponseBody,
		arg.DurationMs,
		arg.Error,
	)
	return err
}
