// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chats.sql

package db

import (
	"context"
)

const createChat = `-- name: CreateChat :one
INSERT INTO chats (chat_id, title) VALUES (?, ?) RETURNING id, chat_id, title, created_at
`

type CreateChatParams struct {
	ChatID int64
	Title  string
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error) {
	row := q.db.QueryRowContext(ctx, createChat, arg.ChatID, arg.Title)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const getChatByChatID = `-- name: GetChatByChatID :one
SELECT id, chat_id, title, created_at FROM chats WHERE chat_id = ?
`

func (q *Queries) GetChatByChatID(ctx context.Context, chatID int64) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChatByChatID, chatID)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const listChats = `-- name: ListChats :many
SELECT id, chat_id, title, created_at FROM chats ORDER BY id
`

func (q *Queries) ListChats(ctx context.Context) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, listChats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Title,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
