// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gas_refills.sql

package db

import (
	"context"
)

const insertGasRefill = `-- name: InsertGasRefill :one
INSERT INTO gas_refills (chain, order_uid, wallet_address, sell_amount, buy_amount, status, user_id, chat_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertGasRefillParams struct {
	Chain         string
	OrderUid      string
	WalletAddress string
	SellAmount    string
	BuyAmount     string
	Status        string
	UserID        int64
	ChatID        int64
}

func (q *Queries) InsertGasRefill(ctx context.Context, arg InsertGasRefillParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertGasRefill,
		arg.Chain,
		arg.OrderUid,
		arg.WalletAddress,
		arg.SellAmount,
		arg.BuyAmount,
		arg.Status,
		arg.UserID,
		arg.ChatID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listPendingGasRefills = `-- name: ListPendingGasRefills :many
SELECT id, chain, order_uid, wallet_address, sell_amount, buy_amount, status, user_id, chat_id, created_at
FROM gas_refills WHERE status = 'open' ORDER BY created_at
`

func (q *Queries) ListPendingGasRefills(ctx context.Context) ([]GasRefill, error) {
	rows, err := q.db.QueryContext(ctx, listPendingGasRefills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GasRefill
	for rows.Next() {
		var i GasRefill
		if err := rows.Scan(
			&i.ID,
			&i.Chain,
			&i.OrderUid,
			&i.WalletAddress,
			&i.SellAmount,
			&i.BuyAmount,
			&i.Status,
			&i.UserID,
			&i.ChatID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGasRefillStatus = `-- name: UpdateGasRefillStatus :exec
UPDATE gas_refills SET status = ? WHERE id = ?
`

type UpdateGasRefillStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdateGasRefillStatus(ctx context.Context, arg UpdateGasRefillStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateGasRefillStatus, arg.Status, arg.ID)
	return err
}
