// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type AddressAssignment struct {
	ID             int64
	AssignedToID   int64
	AssignedToType string
	CreatedAt      time.Time
}

type Chat struct {
	ID        int64
	ChatID    int64
	Title     string
	CreatedAt time.Time
}

type GasRefill struct {
	ID            int64
	Chain         string
	OrderUid      string
	WalletAddress string
	SellAmount    string
	BuyAmount     string
	Status        string
	UserID        int64
	ChatID        int64
	CreatedAt     time.Time
}

type Quote struct {
	ID             int64
	Type           string
	Provider       string
	UserID         int64
	FromAsset      string
	FromChain      string
	ToAsset        string
	Destination    string
	InputAmountUsd float64
	InputAmount    string
	ExpectedOutput string
	Memo           string
	Router         string
	VaultAddress   string
	Expiry         int64
	CreatedAt      time.Time
	ChatID         int64
}

type Topup struct {
	ID         int64
	ShortID    string
	Type       string
	QuoteID    int64
	UserID     int64
	Provider   string
	FromChain  string
	TxHash     string
	Status     string
	CreatedAt  time.Time
	ChatID     int64
	ExternalID string
}

type User struct {
	ID         int64
	TelegramID int64
	Username   string
	CreatedAt  time.Time
}
