// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quotes.sql

package db

import (
	"context"
	"time"
)

const getQuote = `-- name: GetQuote :one
SELECT id, type, provider, user_id, from_asset, from_chain, to_asset, destination,
    input_amount_usd, input_amount, expected_output, memo, router, vault_address, expiry, chat_id, created_at
FROM quotes
WHERE id = ?
`

type GetQuoteRow struct {
	ID             int64
	Type           string
	Provider       string
	UserID         int64
	FromAsset      string
	FromChain      string
	ToAsset        string
	Destination    string
	InputAmountUsd float64
	InputAmount    string
	ExpectedOutput string
	Memo           string
	Router         string
	VaultAddress   string
	Expiry         int64
	ChatID         int64
	CreatedAt      time.Time
}

func (q *Queries) GetQuote(ctx context.Context, id int64) (GetQuoteRow, error) {
	row := q.db.QueryRowContext(ctx, getQuote, id)
	var i GetQuoteRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Provider,
		&i.UserID,
		&i.FromAsset,
		&i.FromChain,
		&i.ToAsset,
		&i.Destination,
		&i.InputAmountUsd,
		&i.InputAmount,
		&i.ExpectedOutput,
		&i.Memo,
		&i.Router,
		&i.VaultAddress,
		&i.Expiry,
		&i.ChatID,
		&i.CreatedAt,
	)
	return i, err
}

const insertQuote = `-- name: InsertQuote :one
INSERT INTO quotes (
    type, provider, user_id, from_asset, from_chain, to_asset, destination,
    input_amount_usd, input_amount, expected_output, memo, router, vault_address, expiry, chat_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertQuoteParams struct {
	Type           string
	Provider       string
	UserID         int64
	FromAsset      string
	FromChain      string
	ToAsset        string
	Destination    string
	InputAmountUsd float64
	InputAmount    string
	ExpectedOutput string
	Memo           string
	Router         string
	VaultAddress   string
	Expiry         int64
	ChatID         int64
}

func (q *Queries) InsertQuote(ctx context.Context, arg InsertQuoteParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertQuote,
		arg.Type,
		arg.Provider,
		arg.UserID,
		arg.FromAsset,
		arg.FromChain,
		arg.ToAsset,
		arg.Destination,
		arg.InputAmountUsd,
		arg.InputAmount,
		arg.ExpectedOutput,
		arg.Memo,
		arg.Router,
		arg.VaultAddress,
		arg.Expiry,
		arg.ChatID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
