// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quotes.sql

package db

import (
	"context"
)

const getQuote = `-- name: GetQuote :one
SELECT id, type, provider, user_id, from_asset, from_chain, to_asset, destination,
    input_amount_usd, input_amount, expected_output, memo, router, vault_address, expiry, created_at
FROM quotes
WHERE id = ?
`

func (q *Queries) GetQuote(ctx context.Context, id int64) (Quote, error) {
	row := q.db.QueryRowContext(ctx, getQuote, id)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Provider,
		&i.UserID,
		&i.FromAsset,
		&i.FromChain,
		&i.ToAsset,
		&i.Destination,
		&i.InputAmountUsd,
		&i.InputAmount,
		&i.ExpectedOutput,
		&i.Memo,
		&i.Router,
		&i.VaultAddress,
		&i.Expiry,
		&i.CreatedAt,
	)
	return i, err
}

const insertQuote = `-- name: InsertQuote :one
INSERT INTO quotes (
    type, provider, user_id, from_asset, from_chain, to_asset, destination,
    input_amount_usd, input_amount, expected_output, memo, router, vault_address, expiry
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertQuoteParams struct {
	Type           string
	Provider       string
	UserID         int64
	FromAsset      string
	FromChain      string
	ToAsset        string
	Destination    string
	InputAmountUsd float64
	InputAmount    string
	ExpectedOutput string
	Memo           string
	Router         string
	VaultAddress   string
	Expiry         int64
}

func (q *Queries) InsertQuote(ctx context.Context, arg InsertQuoteParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertQuote,
		arg.Type,
		arg.Provider,
		arg.UserID,
		arg.FromAsset,
		arg.FromChain,
		arg.ToAsset,
		arg.Destination,
		arg.InputAmountUsd,
		arg.InputAmount,
		arg.ExpectedOutput,
		arg.Memo,
		arg.Router,
		arg.VaultAddress,
		arg.Expiry,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
