// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: topups.sql

package db

import (
	"context"
)

const getTopupByShortID = `-- name: GetTopupByShortID :one
SELECT id, short_id, type, quote_id, user_id, provider, from_chain, tx_hash, status, created_at
FROM topups
WHERE short_id = ?
`

func (q *Queries) GetTopupByShortID(ctx context.Context, shortID string) (Topup, error) {
	row := q.db.QueryRowContext(ctx, getTopupByShortID, shortID)
	var i Topup
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.Type,
		&i.QuoteID,
		&i.UserID,
		&i.Provider,
		&i.FromChain,
		&i.TxHash,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertTopup = `-- name: InsertTopup :one
INSERT INTO topups (short_id, type, quote_id, user_id, provider, from_chain, tx_hash, status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, short_id
`

type InsertTopupParams struct {
	ShortID   string
	Type      string
	QuoteID   int64
	UserID    int64
	Provider  string
	FromChain string
	TxHash    string
	Status    string
}

type InsertTopupRow struct {
	ID      int64
	ShortID string
}

func (q *Queries) InsertTopup(ctx context.Context, arg InsertTopupParams) (InsertTopupRow, error) {
	row := q.db.QueryRowContext(ctx, insertTopup,
		arg.ShortID,
		arg.Type,
		arg.QuoteID,
		arg.UserID,
		arg.Provider,
		arg.FromChain,
		arg.TxHash,
		arg.Status,
	)
	var i InsertTopupRow
	err := row.Scan(&i.ID, &i.ShortID)
	return i, err
}

const listPendingTopups = `-- name: ListPendingTopups :many
SELECT id, short_id, type, quote_id, user_id, provider, from_chain, tx_hash, status, created_at
FROM topups WHERE status = 'pending' ORDER BY created_at
`

func (q *Queries) ListPendingTopups(ctx context.Context) ([]Topup, error) {
	rows, err := q.db.QueryContext(ctx, listPendingTopups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topup
	for rows.Next() {
		var i Topup
		if err := rows.Scan(
			&i.ID,
			&i.ShortID,
			&i.Type,
			&i.QuoteID,
			&i.UserID,
			&i.Provider,
			&i.FromChain,
			&i.TxHash,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTopupStatus = `-- name: UpdateTopupStatus :exec
UPDATE topups SET status = ? WHERE id = ?
`

type UpdateTopupStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdateTopupStatus(ctx context.Context, arg UpdateTopupStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTopupStatus, arg.Status, arg.ID)
	return err
}
