// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: treasury_ledger.sql

package db

import (
	"context"
	"database/sql"
)

const countTreasuryLedger = `-- name: CountTreasuryLedger :one
SELECT COUNT(*) FROM treasury_ledger
`

func (q *Queries) CountTreasuryLedger(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTreasuryLedger)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertTreasuryLedger = `-- name: InsertTreasuryLedger :one
INSERT INTO treasury_ledger (direction, kind, chain, amount_usdc, tx_hash, deposit_address, topup_id, status, note)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertTreasuryLedgerParams struct {
	Direction      string
	Kind           string
	Chain          string
	AmountUsdc     int64
	TxHash         string
	DepositAddress string
	TopupID        sql.NullInt64
	Status         string
	Note           string
}

func (q *Queries) InsertTreasuryLedger(ctx context.Context, arg InsertTreasuryLedgerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertTreasuryLedger,
		arg.Direction,
		arg.Kind,
		arg.Chain,
		arg.AmountUsdc,
		arg.TxHash,
		arg.DepositAddress,
		arg.TopupID,
		arg.Status,
		arg.Note,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listPendingTreasuryOps = `-- name: ListPendingTreasuryOps :many
SELECT id, direction, kind, chain, amount_usdc, tx_hash, deposit_address, topup_id, status, note, created_at
FROM treasury_ledger
WHERE status = 'pending' AND deposit_address != ''
ORDER BY created_at
`

func (q *Queries) ListPendingTreasuryOps(ctx context.Context) ([]TreasuryLedger, error) {
	rows, err := q.db.QueryContext(ctx, listPendingTreasuryOps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TreasuryLedger
	for rows.Next() {
		var i TreasuryLedger
		if err := rows.Scan(
			&i.ID,
			&i.Direction,
			&i.Kind,
			&i.Chain,
			&i.AmountUsdc,
			&i.TxHash,
			&i.DepositAddress,
			&i.TopupID,
			&i.Status,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTreasuryLedger = `-- name: ListTreasuryLedger :many
SELECT id, direction, kind, chain, amount_usdc, tx_hash, deposit_address, topup_id, status, note, created_at
FROM treasury_ledger
ORDER BY created_at DESC, id DESC
LIMIT ?2 OFFSET ?1
`

type ListTreasuryLedgerParams struct {
	Offset int64
	Limit  int64
}

func (q *Queries) ListTreasuryLedger(ctx context.Context, arg ListTreasuryLedgerParams) ([]TreasuryLedger, error) {
	rows, err := q.db.QueryContext(ctx, listTreasuryLedger, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TreasuryLedger
	for rows.Next() {
		var i TreasuryLedger
		if err := rows.Scan(
			&i.ID,
			&i.Direction,
			&i.Kind,
			&i.Chain,
			&i.AmountUsdc,
			&i.TxHash,
			&i.DepositAddress,
			&i.TopupID,
			&i.Status,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTreasuryLedgerStatus = `-- name: UpdateTreasuryLedgerStatus :exec
UPDATE treasury_ledger SET status = ? WHERE id = ?
`

type UpdateTreasuryLedgerStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdateTreasuryLedgerStatus(ctx context.Context, arg UpdateTreasuryLedgerStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTreasuryLedgerStatus, arg.Status, arg.ID)
	return err
}
